version: '3.8'

services:

  config-server:
    build:
      context: ../config-server
      dockerfile: ../docker/Dockerfile.config
    ports:
      - "8888:8888"
    container_name: config-server

  product-service:
    build:
      context: ../product-service
      dockerfile: ../docker/Dockerfile.product
    ports:
      - "8081:8081"
    container_name: product-service
    depends_on:
      - config-server

  order-service:
    build:
      context: ../order-service
      dockerfile: ../docker/Dockerfile.order
    ports:
      - "8082:8082"
    container_name: order-service
    depends_on:
      - config-server

  user-service:
    build:
      context: ../user-service
      dockerfile: ../docker/Dockerfile.user
    ports:
      - "8083:8083"
    container_name: user-service
    depends_on:
      - config-server

  gateway-service:
    build:
      context: ../gateway-service
      dockerfile: ../docker/Dockerfile.gateway
    ports:
      - "8080:8080"
    container_name: gateway-service
    depends_on:
      - product-service
      - order-service
      - user-service
